-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer


-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: ''
    hooks:
    - id: clang-format

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''
    hooks:
    - id: autopep8

-   repo: https://github.com/pycqa/isort
    rev: ''
    hooks:
    - id: isort

-   repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: [--config=./python/setup.cfg]
